### ISSUE TITLE
Wakapi support

### ISSUE THREAD

**Issue by dashezup** [devgianlu/Timeless#37]
[wakapi](https://github.com/muety/wakapi) is a Wakatime-compatible backend, it lacks some features of wakatime (such like leaderboards) but there are some basic APIs are implemented.

You can check Wakapi API at [here](https://wakapi.dev/swagger-ui/)

To have support for wakapi, I think at least it should show an option to specify the `api_url` and `api_key` on start at first. maybe disable some components when some API method is not available.

**Comment by devgianlu** [comment]
I've looked at the API, but I think it lacks too many endpoints to have a functional app. Also there's no way to detect whether an endpoint it missing.

**Comment by dashezup** [comment]
I think the server will response with 404 or something if it's not available (just send a header request maybe).

Or just whitelist available API endpoints when the user choose specify custom API url.

**Comment by devgianlu** [comment]
I am trying to add support for it in #38, but the `https://wakapi.dev/api/compat/wakatime/v1/users/current/summaries` is broken. It says the `start` parameter is missing even if it's correctly specified. 

![image](https://user-images.githubusercontent.com/14827249/116449613-a42f0500-a85a-11eb-98b4-b41282d249df.png)

**Comment by devgianlu** [comment]
Once https://github.com/muety/wakapi/issues/192 is merged. Most of the features of the app should be working, apart from projects, commits, etc...

**Comment by devgianlu** [comment]
Merged! There's stuff that's missing, but not too much. The other required endpoint would be the one for the user data, right now it'll display "anonymous user" instead

When endpoints are added it should start working automatically without an app update needed.

I'll be realising a new version probably tomorrow.

**Comment by ysxninja** [comment]
I'm trying to connect to a local instance of wakapi running on localhost, accessible from my android at an IP like http://192.168.1.1:8080.
When connecting, the app crashes with the error "Failed Loading Data".
