### ISSUE TITLE
Make colors deterministic

### ISSUE THREAD

**Issue by muety** [devgianlu/Timeless#43]
First of all, thanks a lot for your efforts, Timeless is awesome!

This bug is a minor one, but you might want to consider it some time in the future. The colors used in my activity charts seem to be determined randomly, i.e. when I refresh the activity, colors will change. It'd be cool to have the same project (language, editor, ...) always be colored the same way. 

Wakapi and WakaTime use GitHub's [color coding](https://github.com/muety/wakapi/blob/master/data/colors.json) for languages and a fixed set of colors for editors and OSs as well. For projects and machines, Wakapi determines a [random color, but with the entitiy's key as a seed value](https://github.com/muety/wakapi/blob/11b224fc24973d90762963a6c5c790573f5e9758/static/assets/app.js#L334).

**Comment by devgianlu** [comment]
There had already been an attempt at this, but it was implement very well. I have improved the situation by using the colors you provided and improved the overall implementation by separating projects, machines and branches colors.
