### ISSUE TITLE
Can't hide keyboard

### ISSUE THREAD

**Issue by muety** [devgianlu/Timeless#44]
For some weird reason, I can't close my soft keyboard when API key or API URL fields are focused. The down arrow button seems to be hidden. I don't know if this is even related to the app itself, but you might want to have a look.

![image](https://user-images.githubusercontent.com/8978843/116775171-cb0b5800-aa61-11eb-818c-f5f5b7b6400f.png)

**Comment by devgianlu** [comment]
That's strange, it works for me on Android 6 and 11. Which version are you on?

**Comment by muety** [comment]
I'm on Android 11 on a Pixel 3. Same issue occurs on my Pixel 4 XL emulator.

**Comment by devgianlu** [comment]
I tried it myself on a Pixel 3 and the issue I had there was that the navigation buttons on the bottom were hidden by the layout. Should be fixed now.
