### ISSUE TITLE
Projects and commits activity crash on 404

### ISSUE THREAD

**Issue by muety** [devgianlu/Timeless#45]
Projects, commits, public- and private leaderboards currently have no corresponding endpoints in Wakapi (there will be one for projects though, https://github.com/muety/wakapi/issues/196). For leaderboard, an explanatory message is displayed, informing the user of the corresponding feature not being available with the current backend. For projects and commits, however, an activity seems to start and then crash with only a short toast message. Maybe this failure could be a bit more graceful, too.

**Comment by devgianlu** [comment]
The projects one is now able to show some data thanks to the projects endpoint addition. 
The commits one will show a message about the fact that no projects have repositories connected.
